[service]
# In "standalone" mode, the service will run all the components in a single process.
# In "worker" mode, the service will run only the tasker and its dependencies.
# In "api" mode, the service will run only the API and its dependencies.
# In "sub" mode, the service will run only the JetStream subscriber and its dependencies.

# If not running in "standalone" mode, all other mods must still be started independently and connect with each other.
mode = "standalone"
metrics = true

[api]
address = ":5003"
docs = true
jrpc = true
cors = ["https://sarafu.network"]
# These are sample keys, replace them with your own in production.
# openssl genpkey -algorithm ED25519 -out private.pem
# openssl pkey -in private.pem -pubout -out public.pem
public_key = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAHGCyaM2KW5/S31wd+jHuki2QrQw1pyAFUcz888ekiVA=
-----END PUBLIC KEY-----"""
private_key = """
-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIMJ3D6UBk/inMyoPWNPYybNIA0TEinMrWiMEMvoCodXE
-----END PRIVATE KEY-----"""

[postgres]
dsn = "postgres://postgres:postgres@127.0.0.1:5432/eth_custodial"

[workers]
max = 0

[gas]
oracle_type = "static"

[chain]
id = 1337
rpc_endpoint = "http://localhost:8545"
ge_registry = "0xEA7a52e565C43598011cC5f509b8252Eb3e8dbE5"
# Certain chains implement the gas token as an ERC20 token as well. We block any transfer related to it at the API level.
banned_tokens = ["0x471EcE3750Da237f93B8E339c536989b8978a438"]

[jetstream]
endpoint = "nats://127.0.0.1:4222"
id = "eth-custodial-1"
persist_duration_hrs = 48
