[metrics]
enable = true

[api]
address = ":5003"
docs = true
# These are sample keys, replace them with your own in production.
# openssl genpkey -algorithm ED25519 -out private.pem
# openssl pkey -in private.pem -pubout -out public.pem
public_key = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAHGCyaM2KW5/S31wd+jHuki2QrQw1pyAFUcz888ekiVA=
-----END PUBLIC KEY-----"""
private_key = """
-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIMJ3D6UBk/inMyoPWNPYybNIA0TEinMrWiMEMvoCodXE
-----END PRIVATE KEY-----"""

[postgres]
dsn = "postgres://postgres:postgres@127.0.0.1:5432/ge_celo_custodial"

[workers]
max = 0

[gas]
oracle_type = "static"

[chain]
id = 1337
rpc_endpoint = "http://localhost:8545"
ge_registry = "0xE979a64D375F5D363d7cecF3c93B9aFD40Ba9f55"
# Certain chains implement the gas token as an ERC20 token as well. We block any transfer related to it at the API level.
gas_token = "0x471EcE3750Da237f93B8E339c536989b8978a438"

[jetstream]
endpoint = "nats://127.0.0.1:4222"
id = "eth-custodial-1"
persist_duration_hrs = 48
