[metrics]
enable = true

[api]
address = ":5003"
key = "xd"

[postgres]
dsn = "postgres://postgres:postgres@127.0.0.1:5432/ge_celo_custodial"

[workers]
max = 0

[gas]
oracle_type = "static"

[chain]
id = 1337
rpc_endpoint = "http://localhost:8545"
custodial_registration_proxy = "0xf282a3C68A2505a79Fc99f94CE43D9c83230CaE5"

[jetstream]
endpoint = "nats://127.0.0.1:4222"
id = "eth-custodial-1"
