services:
  custodial-pg-store:
    image: postgres:16-alpine
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - custodial-pg:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  custodial-pg:
    driver: local