services:
  devnet:
    image: ghcr.io/paradigmxyz/reth:latest
    restart: unless-stopped
    command: "node --datadir /root/devnet-chaindata --dev --dev.block-time 1s --http --http.addr 0.0.0.0 --ws --ws.addr 0.0.0.0"
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"
    volumes:
      - devnet-chaindata:/root/devnet-chaindata   
  custodial-pg-store:
    image: postgres:16-alpine
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - custodial-pg:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  custodial-river-ui:
    image: ghcr.io/riverqueue/riverui:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@custodial-pg-store:5432/ge_celo_custodial
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      custodial-pg-store:
        condition: service_healthy  

volumes:
  custodial-pg:
    driver: local
  devnet-chaindata:
    driver: local