basePath: /api/v2
definitions:
  api.ErrResponse:
    properties:
      description:
        type: string
      errorCode:
        type: string
      ok:
        type: boolean
    type: object
  api.OKResponse:
    properties:
      description:
        type: string
      ok:
        type: boolean
      result:
        additionalProperties: {}
        type: object
    type: object
  api.TransferRequest:
    properties:
      amount:
        type: string
      from:
        type: string
      to:
        type: string
      tokenAddress:
        type: string
    required:
    - amount
    - from
    - to
    - tokenAddress
    type: object
host: localhost:5003
info:
  contact:
    email: devops@grassecon.org
    name: API Support
    url: https://grassecon.org/pages/contact-us
  description: Interact with the Grassroots Economics Custodial API
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  termsOfService: https://grassecon.org/pages/terms-and-conditions.html
  title: ETH Custodial API
  version: "2.0"
paths:
  /account/create:
    post:
      consumes:
      - '*/*'
      description: Create a new custodial account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a new custodial account
      tags:
      - Account
  /account/status/{address}:
    get:
      consumes:
      - '*/*'
      description: Check a custodial account's status
      parameters:
      - description: Account address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Check a custodial account's status
      tags:
      - Account
  /otx/track/{trackingId}:
    get:
      consumes:
      - '*/*'
      description: Track an OTX's (Origin transaction) chain status
      parameters:
      - description: Tracking ID
        in: path
        name: trackingId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Track an OTX's (Origin transaction) chain status
      tags:
      - OTX
  /system:
    get:
      consumes:
      - '*/*'
      description: Get the current system information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Get the current system information
      tags:
      - System
  /transfer:
    post:
      consumes:
      - application/json
      description: Sign a token transfer request
      parameters:
      - description: Transfer request
        in: body
        name: transferRequest
        required: true
        schema:
          $ref: '#/definitions/api.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Sign a token transfer request
      tags:
      - Sign
securityDefinitions:
  ApiKeyAuth:
    description: Service API Key
    in: header
    name: X-GE-KEY
    type: apiKey
swagger: "2.0"
