basePath: /api/v2
definitions:
  api.ERC20DeployRequest:
    properties:
      decimals:
        type: integer
      initialMintee:
        type: string
      initialSupply:
        type: string
      name:
        type: string
      owner:
        type: string
      symbol:
        type: string
    required:
    - decimals
    - initialMintee
    - initialSupply
    - name
    - owner
    - symbol
    type: object
  api.ErrResponse:
    properties:
      description:
        type: string
      errorCode:
        type: string
      ok:
        type: boolean
    type: object
  api.OKResponse:
    properties:
      description:
        type: string
      ok:
        type: boolean
      result:
        additionalProperties: {}
        type: object
    type: object
  api.PoolDepositRequest:
    properties:
      amount:
        type: string
      from:
        type: string
      poolAddress:
        type: string
      tokenAddress:
        type: string
    required:
    - amount
    - from
    - poolAddress
    - tokenAddress
    type: object
  api.PoolSwapRequest:
    properties:
      amount:
        type: string
      from:
        type: string
      fromTokenAddress:
        type: string
      poolAddress:
        type: string
      toTokenAddress:
        type: string
    required:
    - amount
    - from
    - fromTokenAddress
    - poolAddress
    - toTokenAddress
    type: object
  api.SweepRequest:
    properties:
      from:
        type: string
      to:
        type: string
      tokenAddress:
        type: string
    required:
    - from
    - to
    - tokenAddress
    type: object
  api.TransferRequest:
    properties:
      amount:
        type: string
      from:
        type: string
      to:
        type: string
      tokenAddress:
        type: string
    required:
    - amount
    - from
    - to
    - tokenAddress
    type: object
host: localhost:5003
info:
  contact:
    email: devops@grassecon.org
    name: API Support
    url: https://grassecon.org/pages/contact-us
  description: Interact with the Grassroots Economics Custodial API
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  termsOfService: https://grassecon.org/pages/terms-and-conditions.html
  title: ETH Custodial API
  version: "2.0"
paths:
  /account/create:
    post:
      consumes:
      - '*/*'
      description: Create a new custodial account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a new custodial account
      tags:
      - Account
  /account/otx/{address}:
    get:
      consumes:
      - '*/*'
      description: Get an accounts OTX's (Origin transaction)
      parameters:
      - description: Account
        in: path
        name: address
        required: true
        type: string
      - description: Next
        in: query
        name: next
        type: boolean
      - description: Cursor
        in: query
        name: cursor
        type: integer
      - description: Per page
        in: query
        name: perPage
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Get an accounts OTX's (Origin transaction)
      tags:
      - Account
  /account/status/{address}:
    get:
      consumes:
      - '*/*'
      description: Check a custodial account's status
      parameters:
      - description: Account address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Check a custodial account's status
      tags:
      - Account
  /contracts/erc20:
    post:
      consumes:
      - application/json
      description: ERC20 deploy request
      parameters:
      - description: ERC20 deploy request
        in: body
        name: transferRequest
        required: true
        schema:
          $ref: '#/definitions/api.ERC20DeployRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: ERC20 deploy request
      tags:
      - Contracts
  /otx/track/{trackingId}:
    get:
      consumes:
      - '*/*'
      description: Track an OTX's (Origin transaction) chain status
      parameters:
      - description: Tracking ID
        in: path
        name: trackingId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Track an OTX's (Origin transaction) chain status
      tags:
      - OTX
  /pool/deposit:
    post:
      consumes:
      - application/json
      description: Pool deposit request
      parameters:
      - description: Pool deposit request
        in: body
        name: transferRequest
        required: true
        schema:
          $ref: '#/definitions/api.PoolDepositRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Pool deposit request
      tags:
      - Sign
  /pool/quote:
    post:
      consumes:
      - application/json
      description: Get a pool swap quote
      parameters:
      - description: Get a pool swap quote
        in: body
        name: transferRequest
        required: true
        schema:
          $ref: '#/definitions/api.PoolSwapRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Get a pool swap quote
      tags:
      - Sign
  /pool/swap:
    post:
      consumes:
      - application/json
      description: Pool swap request
      parameters:
      - description: Pool swap request
        in: body
        name: transferRequest
        required: true
        schema:
          $ref: '#/definitions/api.PoolSwapRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Pool swap request
      tags:
      - Sign
  /system:
    get:
      consumes:
      - '*/*'
      description: Get the current system information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Get the current system information
      tags:
      - System
  /token/sweep:
    post:
      consumes:
      - application/json
      description: Sign a token sweep request
      parameters:
      - description: Sweep request
        in: body
        name: sweepRequest
        required: true
        schema:
          $ref: '#/definitions/api.SweepRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Sign a token sweep request
      tags:
      - Sign
  /token/transfer:
    post:
      consumes:
      - application/json
      description: Sign a token transfer request
      parameters:
      - description: Transfer request
        in: body
        name: transferRequest
        required: true
        schema:
          $ref: '#/definitions/api.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.OKResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Sign a token transfer request
      tags:
      - Sign
securityDefinitions:
  TokenAuth:
    description: Service API Token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
